### ISSUE TITLE
Rendering for multiline tags, steps broken

### ISSUE THREAD

**Issue by nehashri** [getgauge/docs.gauge.org#146] opened 2019-07-09 05:34 UTC
The Gauge codeblocks which have multiline tags and steps are marked as comments. 
Also, in some places the code blocks for comments appear in different color. These needs to be addressed.

**Comment by NivedhaSenthil** [comment] 2019-07-12 07:50
Closing as its a duplicate of #152

**Closed by NivedhaSenthil** 2019-07-12 07:50 UTC
